name: Omnis
favicon: null
layout_spectrum: 0.4176853122189641
typography_spectrum: 0.39851854695007205
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.15902437269687653
  lightness: 0.7344880837481469
  saturation: 0.23048113589175045
  rhythmicContrast: 0.5602687860373408
purpose: []
